INCLUDE = ../include

BUILD_STATIC_LIB = -L../src/ -llog

PLATFORM = -DPLATFORM_GE=1

PROJCT_SRC = test_log.c

OBJECT = test_log.o

TARGET = log

CC = gcc

$(TARGET) : $(OBJECT)
	$(CC) $(OBJECT) -o $(TARGET) $(BUILD_STATIC_LIB) $(PLATFORM)

$(OBJECT) : $(PROJCT_SRC)
	$(CC) -c $< -I$(INCLUDE) -o $@ $(BUILD_STATIC_LIB) $(PLATFORM)

clean :
	rm $(TARGET) $(OBJECT)
